"""add_conteudo_bruto_fts

Revision ID: 6bf136ffd1ae
Revises: fc5ca24fa27c
Create Date: 2026-07-17 15:18:48.765299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf136ffd1ae'
down_revision: Union[str, Sequence[str], None] = 'fc5ca24fa27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('conteudo_bruto', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # tabela virtual FTS5 — autogenerate não reflete tabelas virtuais, adicionada manualmente
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS documentos_fts USING fts5(
            chunk_texto,
            documento_id UNINDEXED,
            projeto_id UNINDEXED,
            tokenize = 'unicode61 remove_diacritics 2'
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS documentos_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'conteudo_bruto')
    # ### end Alembic commands ###
